Pull request #508: upcoming [HELIX-187], [HELIX-189] Model library APIv4
Merge in FEE/cloud-manager from model-library-apiv4 to develop

Squashed commit of the following:

commit 2d703b2c1b2c27fa6d727f033de5ae61e66b4ae7
Merge: 0d6ba88ba9 d688161c47
Author: Ola Gold <ogold@akamai.com>
Date:   Wed Jul 1 09:36:46 2026 -0700

    Merge remote-tracking branch 'origin/develop' into model-library-apiv4

commit 0d6ba88ba96e43352888549b497e4e49e014c14d
Merge: ca8660c56f 2266fc6040
Author: Ola Gold <ogold@akamai.com>
Date:   Tue Jun 30 07:25:34 2026 -0700

    Merge remote-tracking branch 'origin/develop' into model-library-apiv4

commit ca8660c56f9b02c4e0c9ed2fb61ac7c7157e3361
Merge: a24672d292 80cd7f9788
Author: Ola Gold <ogold@akamai.com>
Date:   Mon Jun 29 10:54:55 2026 -0700

    Merge remote-tracking branch 'origin/develop' into model-library-apiv4

commit a24672d2928629cf8d1bc461de197b722d3e826d
Author: Rajesh Sharma <rajsharm@akamai.com>
Date:   Mon Jun 29 16:33:28 2026 +0200

    Used crpto to generate rand uuid, used server expired key response to check the key expiry, added unit test, updated mock to have key as '[REDACATED]' after the key creation, not the key-prefix

commit 311d79dbd579a7e60524ed799a0d682b08c3740d
Merge: e4fccace39 c9e9521eac
Author: Ola Gold <ogold@akamai.com>
Date:   Mon Jun 29 07:28:22 2026 -0700

    Merge remote-tracking branch 'origin/develop' into model-library-apiv4

commit e4fccace39738c7eb98a8ccb1f43ac51ca3b547a
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 20:38:30 2026 -0700

    Fix the regression - details drawer should show all the models checked and disable

commit a28dd42c9435b4cbe7356d5e703f8f3cb172a92d
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 20:23:31 2026 -0700

    Add a new test file for playgroundKeyService

commit 4abc5131721eac581b80c3b2779a50546b4cf1c1
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 18:24:19 2026 -0700

    Adress the PR comments:
    Fixed Property 'data' does not exist on type 'NonNullable<TQueryFnData>'
    Import type definitions from @linode/api-v4

commit 5ac070b609f1057c769b8c14a49af7b818cfea23
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 07:55:30 2026 -0700

    Bug Fix: Clicking on Model Library card playground and then back causing Error: Invariant failed: Could not find an active match from "/inference-platform/model-playground"

commit b517ebdd757f34424ef0a33dee6039c03d502d5e
Merge: 3c84d5c8e2 a2d2e5ee67
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 07:30:58 2026 -0700

    Merge remote-tracking branch 'origin/develop' into model-library-apiv4

commit 3c84d5c8e27a1aa4e8cf38ab54cdf6c1b5bb88d4
Author: Ola Gold <ogold@akamai.com>
Date:   Fri Jun 26 07:17:45 2026 -0700

    Added missing Long Context and Code Assistance tolltips values

commit 60bfeb6fab812446600ee022c3644192617f26e9
Author: Ola Gold <ogold@akamai.com>
Date:   Thu Jun 25 15:50:32 2026 -0700

    Create a new changeset file for current PR

commit 5b6a1d56be6cdd5089e02bdca736f7b95b17d175
Author: Ola Gold <ogold@akamai.com>
Date:   Thu Jun 25 14:44:54 2026 -0700

    Update the order of the inference platform tabs

commit 466f5ee42010aed3346ae7641c868dc7ebf1156d
Author: Ola Gold <ogold@akamai.com>
Date:   Thu Jun 25 14:22:36 2026 -0700

    Update the code to use correct API response for mocked and non mocked data for the Model Library

commit d70dcf14a5ede497821d35544671121504f5e7d1
Merge: cf33bf0e42 082d97ca36
Author: Ola Gold <ogold@akamai.com>
Date:   Thu Jun 25 10:24:07 2026 -0700

    Merge branch 'model-library-apiv4' of ssh://git.source.akamai.com:7999/fee/cloud-manager into model-library-apiv4

commit cf33bf0e42f5b447a657d7e6fcf92dc81129f90f
Author: Ola Gold <ogold@akamai.com>
Date:   Thu Jun 25 10:22:01 2026 -0700

    Update the size and colors for the API keys chips

commit 082d97ca36db9b2b856680b1f0c796ba23f1dad4
Author: Rajesh Sharma <rajsharm@akamai.com>
Date:   Thu Jun 25 18:21:22 2026 +0200

    Creating playground keys and state management of the keys, stores playground keys in session storage, checks and verfies key before using. Checking REACT_APP_INFERENCE_API_KEY is defined before creating keys, if defined uses the value of it.

commit ff9bc6708d416179162741c563c3d96623ded2b3
Author: Ola Gold <ogold@akamai.com>
Date:   Wed Jun 24 14:18:45 2026 -0700

    Update the code to use apiv4 endpont for fetching Inference Models.
    Adding new Model Library MSW mock data.